instance_destroy()
instance_create(x, y, obj_slimedead)
instance_create((x + 16), y, obj_slimedebris)
instance_create((x + 16), y, obj_slimedebris)
instance_create((x + 16), y, obj_slimedebris)
instance_create((x + 16), y, obj_slimedebris)
instance_create((x + 16), y, obj_slimedebris)
instance_create((x + 16), y, obj_slimedebris)
instance_create((x + 16), y, obj_slimedebris)
instance_create((x + 16), y, obj_slimedebris)
instance_create((x + 16), y, obj_slimedebris)
instance_create((x + 16), y, obj_slimedebris)
sound_play(sfx_enemyhit, false)

